development:
  user: fedoraAdmin
  password: fedoraAdmin                                        
  url: <%= ENV['FCREPO_URL'] %>
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_URL'] %>
  base_path: /prod
