defaults: &defaults
  locations_url: '' # currently replaced with config/digital_locations.yml
  notifier_email_address: <%= ENV["PMP_MAILER_ADDRESS"] || "pumpkin@iu.edu" %>
  iiif_url: <%= ENV["PMP_IIIF_URL"] || "http://192.168.99.100:5004" %>

  store_original_files: <%= ENV["PMP_STORE_ORIGINAL_FILES"] || true %>
  master_file_service_url: <%= ENV["PMP_MASTER_FILE_SERVICE_URL"] || "http://purl.dlib.indiana.edu/iudl/variations/master" %>
  access_file_service_url: <%= ENV["PMP_ACCESS_FILE_SERVICE_URL"] || "http://purl.dlib.indiana.edu/iudl/variations/access" %>
  purl_redirect_url: <%= ENV["PMP_PURL_REDIRECT_URL"] || "http://server1.variations2.indiana.edu/cgi-bin/access?%s" %>
  create_hocr_files: <%= ENV["PMP_CREATE_HOCR_FILES"] || true %>
  index_hocr_files: <%= ENV["PMP_INDEX_HOCR_FILES"] || true %>

  jp2_recipes:
    default_color: >
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171
      -jp2_space sRGB
      -double_buffering 10
      -num_threads 1
      -no_weights
      Clevels=6
      Clayers=8
      Cblk=\{64,64\}
      Cuse_sop=yes
      Cuse_eph=yes
      Corder=RPCL
      ORGgen_plt=yes
      ORGtparts=R
      Stiles=\{1024,1024\}
    default_gray: >
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171
      -jp2_space sLUM
      -double_buffering 10
      -num_threads 1
      -no_weights
      Clevels=6
      Clayers=8
      Cblk=\{64,64\}
      Cuse_sop=yes
      Cuse_eph=yes
      Corder=RPCL
      ORGgen_plt=yes
      ORGtparts=R
      Stiles=\{1024,1024\}
  events:
    server: 'amqp://localhost:5672'
    exchange: 'plum_events'
  authorized_ldap_groups:
  - <%= ENV["PMP_LDAP_AUTHORIZED_GROUPS"] || 'TestGroup' %>
  ezid:
    mint: false
    update: false
  manifest_builder:
    see_also_hash:
      id: <%= ENV["PMP_MANIFEST_SEE_ALSO_URL"] || 'http://dlib.indiana.edu:9000/iucatextract?maximumRecords=1&operation=searchRetrieve&query=cql.serverChoice=%s&recordSchema=marcxml&version=1.1' %>
      format: 'application/xml'
  metadata:
    url: 'https://purl.dlib.indiana.edu/iudl/iucat/%s'
    editable:
    - :identifier
    - :sort_title
    - :responsibility_note
    - :series
    - :creator
    - :published
    - :publication_place
    - :publisher
    - :issued
    - :physical_description
    - :lccn_call_number
    - :local_call_number
    - :copyright_holder
    - :date_created
    - :subject

development:
  <<: *defaults

test:
  <<: *defaults
  events:
    server:
    exchange: 'plum_events'
  iiif_url: "http://192.168.99.100:5004"
  authorized_ldap_groups: null

production:
  <<: *defaults
  events:
    server: # <%= ENV['PLUM_RABBIT_SERVER'] || 'amqp://localhost:5672' %>
    exchange: "plum_events"

staging:
  <<: *defaults
  events:
    server: <%= ENV['PLUM_RABBIT_SERVER'] || 'amqp://localhost:5672' %>
    exchange: "plum_events"
