# Populates selection list for Holding Location
---
- label: William & Gayle Cook Music Library
  address: 200 South Jordan Ave
  phone_number: (812) 855-2970
  contact_email: libmus@indiana.edu
  gfa_pickup: PW
  staff_only: false
  pickup_location: true
  digital_location: true
  url: https://libraries.indiana.edu/music
  library:
    label: William & Gayle Gook Music Library
    code: libmus
  id: https://libraries.indiana.edu/music
