development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8984/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8986/rest
  base_path: /test
production: &production
  user: <%= ENV["PLUM_FEDORA_USER"] || "fedoraAdmin" %>
  password: <%= ENV["PLUM_FEDORA_PASS"] || "fedoraAdmin" %>
  url: <%= ENV["PLUM_FEDORA_URL"] || "http://localhost:8984/rest" %>
  base_path: /prod
staging:
  <<: *production
  base_path: /staging
