---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - permissions
  - ingest
  - default
  - characterize
  - derivatives
  - audit
  - id_based
  - import_url
  - resolrize
  - upload_set_update
  - lowest
